/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_streamanalyzer_WRAP_H_
#define SWIG_streamanalyzer_WRAP_H_

#include <map>
#include <string>


class SwigDirector_AnalyzerConfiguration : public Strigi::AnalyzerConfiguration, public Swig::Director {

public:
    SwigDirector_AnalyzerConfiguration(PyObject *self);
    virtual ~SwigDirector_AnalyzerConfiguration();
    virtual bool indexFile(char const *path, char const *filename) const;
    virtual bool indexDir(char const *path, char const *filename) const;
    virtual bool useFactory(Strigi::StreamAnalyzerFactory *arg0) const;
    virtual bool useFactory(Strigi::StreamEndAnalyzerFactory *f) const;
    virtual bool useFactory(Strigi::StreamThroughAnalyzerFactory *f) const;
    virtual bool useFactory(Strigi::StreamSaxAnalyzerFactory *f) const;
    virtual bool useFactory(Strigi::StreamEventAnalyzerFactory *f) const;
    virtual bool useFactory(Strigi::StreamLineAnalyzerFactory *f) const;
    virtual bool indexMore() const;
    virtual bool addMoreText() const;
    virtual int64_t maximalStreamReadLength(Strigi::AnalysisResult const &arg0);
    virtual Strigi::AnalyzerConfiguration::FieldType indexType(Strigi::RegisteredField const *f) const;


/* Internal Director utilities */
public:
    bool swig_get_inner(const char* protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }

    void swig_set_inner(const char* protected_method_name, bool val) const
    { swig_inner[protected_method_name] = val;}

private:
    mutable std::map<std::string, bool> swig_inner;


#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (method == NULL) {
          std::string msg = "Method in class AnalyzerConfiguration doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      };
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[10];
#endif

};


class SwigDirector_IndexWriter : public PythonIndexWriter, public Swig::Director {

public:
    SwigDirector_IndexWriter(PyObject *self);
    virtual void startAnalysis(Strigi::AnalysisResult const *arg0);
    virtual void finishAnalysis(Strigi::AnalysisResult const *r);
    virtual void addTriplet(std::string const &subject, std::string const &predicate, std::string const &object);
    virtual void addText(Strigi::AnalysisResult const *r, std::string const &text);
    virtual void addValue(Strigi::AnalysisResult const *r, Strigi::RegisteredField const *field, PyObject *value);
    virtual ~SwigDirector_IndexWriter();


/* Internal Director utilities */
public:
    bool swig_get_inner(const char* protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }

    void swig_set_inner(const char* protected_method_name, bool val) const
    { swig_inner[protected_method_name] = val;}

private:
    mutable std::map<std::string, bool> swig_inner;


#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (method == NULL) {
          std::string msg = "Method in class IndexWriter doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      };
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[5];
#endif

};


class SwigDirector_PythonIndexManager : public PythonIndexManager, public Swig::Director {

public:
    SwigDirector_PythonIndexManager(PyObject *self);
    virtual ~SwigDirector_PythonIndexManager();
    virtual PythonIndexWriter *pythonIndexWriter();


/* Internal Director utilities */
public:
    bool swig_get_inner(const char* protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }

    void swig_set_inner(const char* protected_method_name, bool val) const
    { swig_inner[protected_method_name] = val;}

private:
    mutable std::map<std::string, bool> swig_inner;


#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (method == NULL) {
          std::string msg = "Method in class PythonIndexManager doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      };
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[1];
#endif

};


#endif
